### ISSUE TITLE
MimeTypes dupplicates

### ISSUE THREAD

**Issue by DoluTattoo** [kibook/httpmanager#1]
Hello, not sure if that can be problematic or not but there is several dupplicate indexes in `mime.lua`
![image](https://user-images.githubusercontent.com/47056777/143729083-37fb1727-dab1-4c1b-a282-0a6afd33dd46.png)

**Comment by kibook** [comment]
Thanks! The table was automatically generated from a common MIME type list, which led to these duplicates. They wouldn't cause any issues as Lua will simply ignore duplicate keys, but they might as well be removed.
