### ISSUE TITLE
Limt on number of routes?

### ISSUE THREAD

**Issue by Luke20201** [kibook/httpmanager#4]
Hey, I was wondering if there was a limit on the number of routes?

I've discovered that, after adding more than 5 routes via an export in one resource, only the very last route will register. It's then been a pain even after lowering to 4 routes, to get any connections.

Is this known, or intentional, or is there a way to get 6 routes?

**Comment by Luke20201** [comment]
Attached is a small video demo of what's happening here.
https://user-images.githubusercontent.com/62490330/164949251-dce81175-8cc3-47ff-aabc-15f97ff23a25.mp4

This demo is only 5 routes. It previously work exactly like this until a 6th route was added

**Comment by kibook** [comment]
You should only call `SetHttpHandler` once, and add multiple routes as multiple keys to the `routes` table in one handler:

```lua
SetHttpHandler(exports.httpmanager:createHttpHandler {
	routes = {
		["/discord_kick/(%d+)(%a+)"] = function(req, res, helpers, player, reason)
			...
		end,
		["/discord_restart/(%a+)"] = function(req, res, helpers, script)
			...
		end,
		["/discord_stop/(%a+)"] = function(req, res, helpers, script)
			...
		end,
	}
})
```

I'm not sure why FXServer is limited to specifically 5 HTTP handlers per resource as you seem to have found, but there is not really any reason to have more than one per resource anyways.

Also, be very careful with what you are doing here, you haven't set any authorization for these handlers so anyone will be able to use these routes just like how you are testing them with your web browser.

**Comment by Luke20201** [comment]
> You should only call `SetHttpHandler` once, and add multiple routes as multiple keys to the `routes` table in one handler:
> 
> ```lua
> SetHttpHandler(exports.httpmanager:createHttpHandler {
> 	routes = {
> 		["/discord_kick/(%d+)(%a+)"] = function(req, res, helpers, player, reason)
> 			...
> 		end,
> 		["/discord_restart/(%a+)"] = function(req, res, helpers, script)
> 			...
> 		end,
> 		["/discord_stop/(%a+)"] = function(req, res, helpers, script)
> 			...
> 		end,
> 	}
> })
> ```
> 
> I'm not sure why FXServer is limited to specifically 5 HTTP handlers per resource as you seem to have found, but there is not really any reason to have more than one per resource anyways.
> 
> Also, be very careful with what you are doing here, you haven't set any authorization for these handlers so anyone will be able to use these routes just like how you are testing them with your web browser.

Thank you! Your solution worked perfectly :).
I will address your concern with the authorization! Thanks for the help!
